### PR TITLE
Updated docstrings

### PR DESCRIPTION
**Pull request by AzureFractal**

### CODE REVIEW

**Comment by AzureFractal** [comment]
Other comments: 

- In line 513 of eval_framework.py, we still reference optC_v0. Is this intended?
- In moer.py, we should probably just make get_marginal_util only handle the diagonal case. It's not clean to have a function return different return types based on is_diagonal
- I personally think the docstrings are clunkier than needed. But we can just leave them for now in general

**Comment by jbadsdata** [comment]
> In line 513 of eval_framework.py, we still reference optC_v0. Is this intended?
Yes, for debugging, but we should eventually archive/delete.

> 
In moer.py, we should probably just make get_marginal_util only handle the diagonal case. It's not clean to have a function return different return types based on is_diagonal

Noted

> I personally think the docstrings are clunkier than needed. But we can just leave them for now in general

Noted!

**Comment by jbadsdata** [comment]
@AzureFractal Can you change the target branch to `develop`? Then I'll merge the PR through `develop` to main`.

**Comment by AzureFractal** [comment]
Okay I've created a new PR that targets develop. I'll close this one

**Pull request closed without merging**
